# Generated by Django 4.2.6 on 2023-10-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secretpr", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="member", new_name="user",
        ),
    ]
